version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=binargold
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=nanasuryana335@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db